### ISSUE TITLE
There is no layout icon defined.

### ISSUE THREAD

**Issue by RobSis** [RobSis/treesome#5]

**Comment by jkurei** [comment]
I'd suggest something like [Glyphicons](http://glyphicons.com/)' pine icon. It's CC-By, so attribution would have to be added to the README.md. AFAIK, there would be no problem in making a version with the same color Awesome uses in the layout icons, like so: https://dl.dropboxusercontent.com/u/871486/glyphicons_316_tree_conifer.png
