### ISSUE TITLE
Doesn't work, when more clients have the same PID

### ISSUE THREAD

**Issue by lcpz** [RobSis/treesome#6]
Here's what happens instead:

![20130406164830](https://f.cloud.github.com/assets/1777696/347382/6cbec4dc-9ec9-11e2-9634-ec3fac20a681.png)

**Comment by RobSis** [comment]
Are you sure, that those clients don't have floating property set to true? 

Would you mind sending your rc.lua?

**Comment by lcpz** [comment]
Here's my rc.lua:
https://github.com/copycat-killer/awesome-copycats/blob/master/rc.lua.blackburn

**Comment by juliapath** [comment]
That only happens with urxvtc.  If you urxvt it works just fine.  urxvt is a terminal emulator, that can be used with one daemon and many clients (urxvtd and urxvtc) instead of one process per terminal.

**Comment by lcpz** [comment]
You're right.

Still, this is something that needs to be fixed.
